version: "3.8"

services:
  app:
    build: .
    container_name: go_app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - PORT=8080
      - MONGO_URI=mongodb://mongo:27017/college-bazar
      - MONGO_DB_NAME=college-bazar
    networks:
      - app_network

  mongo:
    image: mongo:6
    container_name: college_bazar_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

volumes:
  mongo_data:

networks:
  app_network:
